apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: showtime-doppler-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: showtime-doppler-token-secret
    namespace: showtime
  project: cinephoria-showtime-service
  config: dev
  managedSecret:
    name: showtime-secret
    namespace: showtime
    type: Opaque