apiVersion: v1
kind: Service
metadata:
  name: showtime-service
  namespace: showtime
spec:
  selector:
    app: showtime
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP