docker_build('saltman0/nodejs-showtime:1.0.0', '../../CinephoriaShowtimeService')

k8s_resource(
    new_name='showtime-nodejs',
    workload='showtime-nodejs-deployment',
    objects=['showtime-doppler-secret', 'showtime', 'showtime-nodejs-referencegrant', 'showtime-doppler-token-secret'],
    labels=["backend"]
)