docker_build('saltman0/cinephoria-showtime:latest', '../../CinephoriaShowtimeService')

k8s_resource(
    new_name='showtime',
    workload='showtime-deployment',
    objects=['showtime-doppler-secret', 'showtime', 'showtime-referencegrant', 'showtime-doppler-token-secret'],
    labels=["backend"]
)