apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: booking-postgresql-scheduled-backup
  namespace: user
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-with-backup-config