apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq-system
  labels:
    app: rabbitmq
spec:
  service:
    type: LoadBalancer
  rabbitmq:
    additionalConfig: |
      default_user=Saltman
      default_pass=B9jgWA56WKMH46fukxc1NP83Q0TgKEQbAUqd1z947Thwjc5rJWSv48u5NuaUwjRz
  replicas: 3