apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq-system
  labels:
    app: rabbitmq
spec:
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
  replicas: 3