apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastructure-nodejs-deployment
  namespace: infrastructure
  annotations:
    secrets.doppler.com/reload: 'true'
  labels:
    app: infrastructure-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infrastructure-nodejs
  template:
    metadata:
      name: infrastructure-nodejs
      labels:
        app: infrastructure-nodejs
    spec:
      containers:
        - name: infrastructure-nodejs
          image: saltman0/nodejs-infrastructure:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: PORT
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: POSTGRES_URL
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: POSTGRES_DB
            - name: IS_VERBOSE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: IS_VERBOSE_ENABLED
            - name: IS_SSL_ENABLED
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: IS_SSL_ENABLED
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: JWT_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: JWT_SECRET
            - name: RABBITMQ_IP
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: RABBITMQ_IP
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infrastructure-secret
                  key: RABBITMQ_PASSWORD
      restartPolicy: Always