apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: infrastructure-doppler-secret
  namespace: doppler-operator-system
  labels:
    app: infrastructure-nodejs
spec:
  tokenSecret:
    name: infrastructure-doppler-token-secret
  managedSecret:
    name: infrastructure-secret
    namespace: infrastructure
    type: Opaque