apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: infrastructure-doppler-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: infrastructure-doppler-token-secret
    namespace: infrastructure
  project: cinephoria-infrastructure-service
  config: dev
  managedSecret:
    name: infrastructure-secret
    namespace: infrastructure
    type: Opaque