apiVersion: v1
kind: Service
metadata:
  name: infrastructure-nodejs-service
  namespace: infrastructure
spec:
  selector:
    app: infrastructure-nodejs
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP