docker_build('saltman0/cinephoria-infrastructure', '../../CinephoriaInfrastructureService')

k8s_resource(
    new_name='infrastructure',
    workload='infrastructure-deployment',
    objects=['infrastructure-doppler-secret', 'infrastructure', 'infrastructure-referencegrant', 'infrastructure-doppler-token-secret'],
    labels=["backend"]
)