docker_build('saltman0/nodejs-infrastructure:dev', '../../CinephoriaInfrastructureService')

k8s_resource(
    new_name='infrastructure-nodejs',
    workload='infrastructure-nodejs-deployment',
    objects=['infrastructure-doppler-secret', 'infrastructure', 'infrastructure-nodejs-referencegrant', 'infrastructure-doppler-token-secret'],
    labels=["backend"]
)