apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: gateway
spec:
  secretName: kong-gateway-tls-secret
  dnsNames:
    - cinephoria.lol
  issuerRef:
    name: letsencrypt-gateway
    kind: ClusterIssuer