k8s_resource(
    new_name='kong',
    objects=['kong-gateway-class', 'kong-gateway', 'letsencrypt-gateway', 'letsencrypt-certificate',
    'kong-httproute-booking', 'kong-httproute-dashboard', 'kong-httproute-graphql', 'kong-httproute-infrastructure',
    'kong-httproute-movie', 'kong-httproute-showtime', 'kong-httproute-user', 'gateway'],
    labels=["backend"]
)

if not os.path.exists("./Plugins/JWT") :
    fail("JWT directory does not exists !")
include('./Plugins/JWT/Tiltfile')