apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: graphql-doppler-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: graphql-doppler-token-secret
    namespace: graphql-namespace
  project: cinephoria-graphql-service
  config: dev
  managedSecret:
    name: graphql-secret
    namespace: graphql-namespace
    type: Opaque