apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: graphql-namespace
spec:
  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP