docker_build('saltman0/cinephoria-graphql:latest', '../../CinephoriaGraphQL')

k8s_resource(
    new_name='graphql',
    workload='graphql-deployment',
    objects=['graphql-doppler-secret', 'graphql', 'graphql-referencegrant', 'graphql-doppler-token-secret'],
    labels=["backend"]
)