apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-nodejs-deployment
  namespace: booking
  annotations:
    secrets.doppler.com/reload: 'true'
  labels:
    app: booking-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-nodejs
  template:
    metadata:
      name: booking-nodejs
      labels:
        app: booking-nodejs
    spec:
      containers:
        - name: booking-nodejs
          image: saltman0/nodejs-booking:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              protocol: TCP
          #volumeMounts:
            #- mountPath: "/mnt/data"
              #name: booking-postgresql-database
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: PORT
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: POSTGRES_DB
            - name: IS_VERBOSE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: IS_VERBOSE_ENABLED
            - name: IS_SSL_ENABLED
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: IS_SSL_ENABLED
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: JWT_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: JWT_SECRET
            - name: RABBITMQ_IP
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: RABBITMQ_IP
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-secret
                  key: RABBITMQ_PASSWORD
      #volumes:
        #- name: booking-postgresql-database
          #persistentVolumeClaim:
            #claimName: booking-postgresql-persistentvolumeclaim
      restartPolicy: Always