apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: booking-doppler-secret
  namespace: doppler-operator-system
  labels:
    app: booking-nodejs
spec:
  tokenSecret:
    name: booking-doppler-token-secret
    namespace: booking
  project: cinephoria-booking-service
  config: dev
  managedSecret:
    name: booking-secret
    namespace: booking
    type: Opaque