apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: booking
spec:
  selector:
    app: booking
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP