apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-postgresql-persistentvolumeclaim
  namespace: booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: booking-postgresql-storageclass