apiVersion: v1
kind: PersistentVolume
metadata:
  name: booking-postgresql-persistentvolume
  namespace: booking
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: booking-postgresql-storageclass
  hostPath:
    path: /mnt/data