apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: booking-postgresql-storageclass
  namespace: booking
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi-driver.example-vendor.example
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer