apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: movie-doppler-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: movie-doppler-token-secret
    namespace: movie
  project: cinephoria-movie-service
  config: dev
  managedSecret:
    name: movie-secret
    namespace: movie
    type: Opaque