apiVersion: v1
kind: Service
metadata:
  name: movie-nodejs-service
  namespace: movie
spec:
  selector:
    app: movie-nodejs
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP