docker_build('saltman0/cinephoria-movie', '../../CinephoriaMovieService')

k8s_resource(
    new_name='movie',
    workload='movie-deployment',
    objects=['movie-doppler-secret', 'movie', 'movie-referencegrant', 'movie-doppler-token-secret'],
    labels=["backend"]
)