docker_build('saltman0/cinephoria-movie-service:latest', '../../CinephoriaMovieService')

k8s_resource(
    new_name='movie-nodejs',
    workload='movie-nodejs-deployment',
    objects=['movie-doppler-secret', 'movie', 'movie-nodejs-referencegrant', 'movie-doppler-token-secret'],
    labels=["backend"]
)