k8s_resource(
    new_name='argocd',
    objects=['argocd', 'argocd-application-booking', 'argocd-application-graphql', 'argocd-application-infrastructure',
    'argocd-application-movie', 'argocd-application-showtime', 'argocd-application-user'],
    labels=["backend"]
)