apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kong-httproute-user
  namespace: gateway
spec:
  parentRefs:
    - name: kong-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /login
        - path:
            type: PathPrefix
            value: /password
        - path:
            type: PathPrefix
            value: /user
      backendRefs:
        - name: user-service
          namespace: user
          kind: Service
          port: 3004