apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: user
  annotations:
    secrets.doppler.com/reload: 'true'
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: saltman0/cinephoria-user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "400Mi"
            limits:
              cpu: "250m"
              memory: "500Mi"
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: PORT
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_DB
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_URL
            - name: IS_VERBOSE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: IS_VERBOSE_ENABLED
            - name: IS_SSL_ENABLED
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: IS_SSL_ENABLED
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_SECRET
            - name: RABBITMQ_IP
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: RABBITMQ_IP
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: RABBITMQ_PASSWORD
      restartPolicy: Always