apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: user-doppler-secret
  namespace: doppler-operator-system
  labels:
    app: user-nodejs
spec:
  tokenSecret:
    name: user-doppler-token-secret
  managedSecret:
    name: user-secret
    namespace: user
    type: Opaque