apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: user-doppler-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: user-doppler-token-secret
    namespace: user
  project: cinephoria-user-service
  config: dev
  managedSecret:
    name: user-secret
    namespace: user
    type: Opaque