apiVersion: v1
kind: Secret
metadata:
  name: user-doppler-token-secret
  namespace: doppler-operator-system
data:
  serviceToken: "ZHAuc3QuZGV2LlRIRERTNXVjdlNNSG1pbFVlZ1pnTXk4NndFcnc2UWhVUVRVSlViZktLeFA="