apiVersion: v1
kind: Service
metadata:
  name: user-nodejs-service
  namespace: user
spec:
  selector:
    app: user-nodejs
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP