docker_build('saltman0/cinephoria-user:latest', '../../CinephoriaUserService')

k8s_resource(
    new_name='user',
    workload='user-deployment',
    objects=['user-doppler-secret', 'user', 'user-referencegrant', 'user-doppler-token-secret'],
    labels=["backend"]
)