docker_build('saltman0/nodejs-user:dev', '../../CinephoriaUserService')

k8s_resource(
    new_name='user-nodejs',
    workload='user-nodejs-deployment',
    objects=['user-doppler-secret', 'user', 'user-nodejs-referencegrant', 'user-doppler-token-secret'],
    labels=["backend"]
)