apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kong-httproute-booking
  namespace: gateway
spec:
  parentRefs:
    - name: kong-gateway
      sectionName: https
    - name: kong-gateway
      sectionName: http
  hostnames:
  - "cinephoria.lol"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /booking
        - path:
            type: PathPrefix
            value: /payment
      backendRefs:
        - name: booking-service
          namespace: booking
          kind: Service
          port: 3001