apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kong-httproute-booking
  namespace: gateway
spec:
  parentRefs:
    - name: kong-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /booking
      backendRefs:
        - name: booking-nodejs-service
          namespace: booking
          kind: Service
          port: 3001