apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kong-httproute-infrastructure
  namespace: gateway
  annotations:
    konghq.com/plugins: jwt-plugin
spec:
  parentRefs:
    - name: kong-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /cinema
        - path:
            type: PathPrefix
            value: /hall
        - path:
            type: PathPrefix
            value: /incident
      backendRefs:
        - name: infrastructure-nodejs-service
          namespace: infrastructure
          kind: Service
          port: 3005